[package]
name = "youtube_dl_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.12.1"
tokio = { version = "1.0", features = ["full"] }
youtube_dl = "0.10.0"
futures = "0.3"
nfd2 = "0.1"
