[package]
name = "youtube_dl_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["advanced"] }
tokio = { version = "1.38.0", features = ["full"] }
youtube_dl = "0.10.0"
futures = "0.3"
nfd2 = "0.3.1"
async-std = "1.10.0"
